# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: jquery-ticker-rails 0.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "jquery-ticker-rails"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Dan Garland", "Glen Smith"]
  s.date = "2015-09-02"
  s.description = "A gem that packages the assets for Jquery News Ticker http://www.jquerynewsticker.com/"
  s.email = "dan@dangarland.co.uk"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/demo.js",
    "app/assets/javascripts/jquery-ticker.js",
    "jquery-ticker-rails.gemspec",
    "lib/jquery-ticker-rails.rb",
    "lib/jquery-ticker-rails/rails.rb",
    "lib/jquery-ticker-rails/rails/engine.rb",
    "test/demo_app/Gemfile",
    "test/demo_app/Gemfile.lock",
    "test/demo_app/README.rdoc",
    "test/demo_app/Rakefile",
    "test/demo_app/app/assets/images/.keep",
    "test/demo_app/app/assets/javascripts/application.js",
    "test/demo_app/app/assets/stylesheets/application.css",
    "test/demo_app/app/controllers/application_controller.rb",
    "test/demo_app/app/controllers/concerns/.keep",
    "test/demo_app/app/helpers/application_helper.rb",
    "test/demo_app/app/mailers/.keep",
    "test/demo_app/app/models/.keep",
    "test/demo_app/app/models/concerns/.keep",
    "test/demo_app/app/views/layouts/application.html.erb",
    "test/demo_app/bin/bundle",
    "test/demo_app/bin/rails",
    "test/demo_app/bin/rake",
    "test/demo_app/bin/setup",
    "test/demo_app/bin/spring",
    "test/demo_app/config.ru",
    "test/demo_app/config/application.rb",
    "test/demo_app/config/boot.rb",
    "test/demo_app/config/environment.rb",
    "test/demo_app/config/environments/development.rb",
    "test/demo_app/config/environments/production.rb",
    "test/demo_app/config/environments/test.rb",
    "test/demo_app/config/initializers/assets.rb",
    "test/demo_app/config/initializers/backtrace_silencers.rb",
    "test/demo_app/config/initializers/cookies_serializer.rb",
    "test/demo_app/config/initializers/filter_parameter_logging.rb",
    "test/demo_app/config/initializers/inflections.rb",
    "test/demo_app/config/initializers/mime_types.rb",
    "test/demo_app/config/initializers/session_store.rb",
    "test/demo_app/config/initializers/wrap_parameters.rb",
    "test/demo_app/config/locales/en.yml",
    "test/demo_app/config/routes.rb",
    "test/demo_app/config/secrets.yml",
    "test/demo_app/db/seeds.rb",
    "test/demo_app/lib/assets/.keep",
    "test/demo_app/lib/tasks/.keep",
    "test/demo_app/log/.keep",
    "test/demo_app/public/404.html",
    "test/demo_app/public/422.html",
    "test/demo_app/public/500.html",
    "test/demo_app/public/favicon.ico",
    "test/demo_app/public/robots.txt",
    "test/demo_app/vendor/assets/javascripts/.keep",
    "test/demo_app/vendor/assets/stylesheets/.keep"
  ]
  s.homepage = "http://github.com/dmgarland/jquery-ticker-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.3"
  s.summary = "A Rails sprockets-compatible gem to package Jquery News Ticker"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

